DROP TABLE ACCOUNT;
CREATE TABLE ACCOUNT(
	ACCNUMBER NUMBER(10) PRIMARY KEY,
	NAME VARCHAR2(20) NOT NULL,
	BALANCE NUMBER NOT NULL
);

INSERT INTO ACCOUNT
VALUES(11111, '연부자', 200);

INSERT INTO ACCOUNT
VALUES(22222, '연흥부', 0);

SELECT * FROM ACCOUNT;